### PR TITLE
Feat/fix periodic test breakage

### PR DESCRIPTION
**Pull request by KevinDanikowski**
issue with periodic test failure was due to folders being deleted containing the same name `tmp` from the two different test files. I solved it by using a random int in the name for the folder creation.

### CODE REVIEW

**Comment by jamesxliu** [comment]
Interesting, so this makes me wonder if the introduction of `nyc` changed the timing of the `afterEach/afterAll` hooks containing rimraf cbs clearing the tmpdirs

**Comment by jamesxliu** [comment]
The tests aren't breaking on the master branch right? Just breaking in the other pull request branch. Which introduces `nyc` into the test runner mix.

**Comment by KevinDanikowski** [comment]
@jamesxliu  it breaks on master. it only works periodically. i don't believe it has to do with nyc but perhaps it could.

**Comment by jamesxliu** [comment]
Whoah, haven't run into that. Pretty hilarious though, I pulled down the branch to reproduce the issue, tests pass, I switch to the fix/code coverage branch and kablammo, build failures in `/tmp`

**Comment by amclin** [comment]
It happens for me when I switch branches even without NYC involved. Perhaps running ‘npm install’ in tmp is doing something that conflicts with node_modules in the parent folder. But I have. I explanation why that would have worked fine in the past.

**Pull request closed without merging**
